# DB
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=jBDINEjTiFMXUBOMIzCNZSamWSsjkIXc
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hikari CP
spring.datasource.hikari.maximum-pool-size=8


cloudinary.cloud-name=dttf9otf4
cloudinary.api-key=585329274292521
cloudinary.api-secret=X7z5N5UR7612Z01c9XfybOw9VNI

jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VucyEhIQ==

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

# === ДИАГНОСТИКА ===
logging.level.root=INFO
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
